### PR TITLE
Remove [[ExecutionContext]]

### PR DESCRIPTION
**Pull request by leobalter**
cc @syg @caridy @rwaldron

### CODE REVIEW

**Review by littledan — APPROVED** [review]
This patch looks like a correct way to implement @syg's [suggestion](https://github.com/tc39/proposal-realms/issues/304#issuecomment-842736704), but I don't understand the motivation for the change. Stashing an execution context is a sort of common technique to make it easier to get into a Realm, e.g., also found in HTML's [environment settings objects](https://html.spec.whatwg.org/#environment-settings-object).

**Comment by leobalter** [comment]
My only goal is unblock all the way to Stage 4, so I don't have a strong preference for this PR or otherwise.

Somehow this proposed approach makes `importValue` a bit closer to `Realm#evaluate`. 

I'm also pretty confident we're going to eventually rename the `GetNewRealmContext`.

**Comment by leobalter** [comment]
Pinging @syg as I want to make sure this address his feedback.

**Comment by leobalter** [comment]
pinging the @tc39/ecma262-editors here. This PR has no observable changes, but matches a request from @syg on the Stage 3 review. I'd like to confirm this is the desired direction for the eventual PR to ECMA-262.

**Comment by caridy** [comment]
@ptomato is this ready for review? what is the latest here?

**Comment by ptomato** [comment]
@caridy I rebased it the other day, but I don't know the context of the original request, so maybe @leobalter or @syg should have a look before merging it.

**Comment by caridy** [comment]
maybe @nicolo-ribaudo has opinions about this change.

**Review by nicolo-ribaudo — APPROVED** [review]
This seems good to me, I actually prefer the new approach of creating a fresh EC every time rather than just creating fresh environment records to attach to it.

**Comment by ptomato** [comment]
Unfortunately this conflicted with #409 merged soon after your review @nicolo-ribaudo. I've rebased it and fixed the conflicts. Should be good to go, but I'd appreciate if you took another quick look at `new ShadowRealm()` where the conflict was.

**Review by caridy — APPROVED** [review]
LGTM

**Pull request merged**
